#!/usr/bin/env bash

NO_FORMAT="\033[0m"
C_RED="\033[38;5;9m"
F_BOLD="\033[1m"

[[ $1 == '-stub' ]] \
    && stub='-stub' \
    || stub=''

[[ $1 == '-stub' ]] \
    && echo 'Executing with -stub' \
    || echo -e "${C_RED}${F_BOLD}Executing without -stub${NO_FORMAT}"

nextflow \
    main.nf \
    -profile local,docker \
    -resume \
    $stub \
    -params-file conf/test_params.json \
    --eggnogmapper_db_dir ../../dbs/emapperdb/5.0.2 \
    --eggnogmapper_tax_scope 33090
